const Strings = {
  copy: {
    "en-US": "Copy",
    "pt-BR": "Copiar",
    "ru-RU": "копия",
    "ko-KR": "부",
    "ja-JP": "コピー",
    "it-IT": "Copia",
    "hu-HU": "Másol",
    "fr-FR": "Copie",
    "es-ES": "Copia",
    "de-DE": "Kopieren",
    "tr-TR": "Kopyala",
  },
  copyN: {
    "en-US": "Copy many",
    "pt-BR": "Copiar vários",
    "ru-RU": "Копировать много",
    "ko-KR": "많은 복사",
    "ja-JP": "多数のコピー",
    "it-IT": "Copia molti",
    "hu-HU": "Sok másolat",
    "fr-FR": "Copier beaucoup",
    "es-ES": "Copia muchos",
    "de-DE": "Viele kopieren",
    "tr-TR": "Çok kopyala",
  },
  batch: {
    "en-US": "Batch copy",
    "pt-BR": "Copiar em lote",
    "ru-RU": "Пакетное копирование",
    "ko-KR": "일괄 복사",
    "ja-JP": "バッチコピー",
    "it-IT": "Copia batch",
    "hu-HU": "Tömegmásolás",
    "fr-FR": "Copie en lot",
    "es-ES": "Copia en bloque",
    "de-DE": "Stapelkopie",
    "tr-TR": "Toplu kopyala",
  },
  playerInfo: {
    "en-US": "Some item IDs may not fit in the player's name.",
    "pt-BR": "Alguns IDs de itens podem não caber no nome do jogador.",
    "ru-RU":
      "Некоторые идентификаторы предметов могут не помещаться в имя игрока.",
    "ko-KR": "일부 아이템 ID는 플레이어 이름에 맞지 않을 수 있습니다.",
    "ja-JP": "一部のアイテムIDはプレイヤーの名前に収まらない場合があります。",
    "it-IT":
      "Alcuni ID degli oggetti potrebbero non adattarsi al nome del giocatore.",
    "hu-HU": "Néhány elemazonosító nem fér bele a játékos nevébe.",
    "fr-FR":
      "Certains identifiants d'objets peuvent ne pas tenir dans le nom du joueur.",
    "es-ES": "Algunos IDs de objetos pueden no caber en el nombre del jugador.",
    "de-DE":
      "Einige Gegenstands-IDs passen möglicherweise nicht in den Namen des Spielers.",
    "tr-TR": "Bazı öğe kimlikleri oyuncunun adına sığmayabilir.",
  },
  debugFileInfo: {
    "en-US":
      "If the option isn't available in your save file, ensure you have slept at least one day in version 1.6.9 or later.",
    "pt-BR":
      "Se a opção não estiver disponível no seu arquivo de save, certifique-se de ter dormido pelo menos um dia na versão 1.6.9 ou posterior.",
    "ru-RU":
      "Если опция недоступна в вашем файле сохранения, убедитесь, что вы спали хотя бы один день в версии 1.6.9 или позднее.",
    "ko-KR":
      "옵션이 저장 파일에 없는 경우 버전 1.6.9 이상에서 하루 이상 잤는지 확인하십시오.",
    "ja-JP":
      "オプションがセーブファイルにない場合は、バージョン1.6.9以降で少なくとも1日寝たことを確認してください。",
    "it-IT":
      "Se l'opzione non è disponibile nel file di salvataggio, assicurati di aver dormito almeno un giorno nella versione 1.6.9 o successiva.",
    "hu-HU":
      "Ha az opció nem érhető el a mentési fájlban, győződj meg róla, hogy legalább egy napig aludtál a 1.6.9-es vagy újabb verzióban.",
    "fr-FR":
      "Si l'option n'est pas disponible dans votre fichier de sauvegarde, assurez-vous d'avoir dormi au moins un jour en version 1.6.9 ou ultérieure.",
    "es-ES":
      "Si la opción no está disponible en tu archivo de guardado, asegúrate de haber dormido al menos un día en la versión 1.6.9 o posterior.",
    "de-DE":
      "Wenn die Option in Ihrer Speicherdatei nicht verfügbar ist, stellen Sie sicher, dass Sie mindestens einen Tag in Version 1.6.9 oder später geschlafen haben.",
    "tr-TR":
      "Seçenek kayıt dosyanızda mevcut değilse, en az bir gün 1.6.9 veya sonraki sürümünde uyuduğunuzdan emin olun.",
  },
  image: {
    "en-US": "Image",
    "pt-BR": "Imagem",
    "ru-RU": "Изображение",
    "ko-KR": "영상",
    "ja-JP": "画像",
    "it-IT": "Immagine",
    "hu-HU": "Kép",
    "fr-FR": "Image",
    "es-ES": "Imagen",
    "de-DE": "Bild",
    "tr-TR": "Resim",
  },
  item: {
    "en-US": "Item",
    "pt-BR": "Item",
    "ru-RU": "Пункт",
    "ko-KR": "항목",
    "ja-JP": "項目",
    "it-IT": "Articolo",
    "hu-HU": "Elem",
    "fr-FR": "Article",
    "es-ES": "Artículo",
    "de-DE": "Artikel",
    "tr-TR": "Öğe",
  },
  actions: {
    "en-US": "Actions",
    "pt-BR": "Ações",
    "ru-RU": "Действия",
    "ko-KR": "행동",
    "ja-JP": "アクション",
    "it-IT": "Azioni",
    "hu-HU": "Cselekvések",
    "fr-FR": "Actions",
    "es-ES": "Acciones",
    "de-DE": "Aktionen",
    "tr-TR": "Eylemler",
  },
  description1: {
    "en-US":
      "Tool developed by <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> to help you find the IDs of items in Stardew Valley <b>updated for the 1.6 update</b>.",
    "pt-BR":
      "Ferramenta desenvolvida por <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> para ajudar você a encontrar os IDs dos itens em Stardew Valley <b>atualizada para a versão 1.6</b>.",
    "ru-RU":
      "Инструмент, разработанный <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a>, чтобы помочь вам найти идентификаторы предметов в Stardew Valley <b>обновлено для обновления 1.6</b>.",
    "ko-KR":
      "<a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a>가 개발한 도구로, 스타듀 밸리의 항목 ID를 찾는 데 도움이 됩니다 <b>1.6 업데이트에 대한 업데이트</b>.",
    "ja-JP":
      "<a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a>によって開発されたツールで、Stardew ValleyのアイテムのIDを見つけるのに役立ちます <b>1.6アップデート用に更新</b>.",
    "it-IT":
      "Strumento sviluppato da <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> per aiutarti a trovare gli ID degli oggetti in Stardew Valley <b>aggiornato per l'aggiornamento 1.6</b>.",
    "hu-HU":
      "<a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> által kifejlesztett eszköz, amely segít megtalálni a Stardew Valley elemek azonosítóit <b>frissítve a 1.6 frissítéshez</b>.",
    "fr-FR":
      "Outil développé par <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> pour vous aider à trouver les identifiants des éléments dans Stardew Valley <b>mis à jour pour la mise à jour 1.6</b>.",
    "es-ES":
      "Herramienta desarrollada por <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> para ayudarte a encontrar los IDs de los objetos en Stardew Valley <b>actualizado para la actualización 1.6</b>.",
    "de-DE":
      "Tool entwickelt von <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a>, um Ihnen zu helfen, die IDs von Gegenständen in Stardew Valley zu finden <b>aktualisiert für das 1.6-Update</b>.",
    "tr-TR":
      "Stardew Valley'deki öğelerin kimliklerini bulmanıza yardımcı olmak için <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> tarafından geliştirilen araç <b>1.6 güncellemesi için güncellendi</b>.",
  },
  spawn: {
    "en-US": "Spawning items",
    "pt-BR": "Spawnando itens",
    "ru-RU": "Появление предметов",
    "ko-KR": "아이템 생성",
    "ja-JP": "アイテムの生成",
    "it-IT": "Generazione di oggetti",
    "hu-HU": "Elemek előhozása",
    "fr-FR": "Apparition d'objets",
    "es-ES": "Aparición de objetos",
    "de-DE": "Gegenstände erscheinen",
    "tr-TR": "Öğeleri doğurmak",
  },
  description2: {
    "en-US":
      'You can spawn items by appending the item ID to your character\'s name and then talking to NPCs, or by <b>buying a pet from Marnie</b> appending the item ID to its name.<br><br>During early game you can easily trigger character\'s name spawns by <b> talking to Gus via phone</b> (or Pierre before 12:00) and after unlocking the cinema you can spam it by<b> inviting Jodi with a <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> to the movie theater</b> (fastest spawn rate).<br><br>Be aware that certain item IDs <b>may exceed the pet\'s name character limit</b>. In such instances, you can use the copy button provided by this tool to bypass the limit. It works by breaking lines to fit the codes into Marnie\'s text box width and removing the line breaks using the new <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">dialogue command</a>.<br><br><b>Warning: Use the item IDs below at your own risk. Doing so may affect your gaming experience.',
    "pt-BR":
      'Você pode spawnar itens adicionando o ID do item ao nome do seu personagem e então falando com NPCs, ou <b>comprando um pet da Marnie</b> adicionando o ID do item ao nome dele.<br><br>No início do jogo você pode facilmente spawnar itens com o nome do personagem falando com o Gus pelo <b>telefone</b> (ou com o Pierre antes das 12:00) e após desbloquear o cinema você pode spammar o spawn de itens convidando a Jodi com um <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> para o cinema (maior taxa de spawn).<br><br>Tenha em mente que certos IDs de item <b>podem exceder o limite de caracteres do nome do pet</b>. Em tais casos, você pode usar o botão de copiar fornecido por esta ferramenta para burlar o limite. Ele funciona dividindo as linhas para caberem na largura da caixa de texto da Marnie e removendo as quebras de linha usando o novo <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">comando de diálogo</a>.<br><br><b>Aviso: Use os IDs de item abaixo por sua própria conta e risco. Fazer isso pode afetar sua experiência de jogo.',
    "ru-RU":
      'Вы можете вызывать предметы, добавляя идентификатор предмета к имени вашего персонажа, а затем разговаривая с NPC, или <b>покупая питомца у Марни</b>, добавляя идентификатор предмета к его имени.<br><br>В начале игры вы можете легко вызвать предметы по имени персонажа, <b>разговаривая с Гасом по телефону</b> (или с Пьером до 12:00), а после разблокировки кинотеатра вы можете спамить это, пригласив Джоди с <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Любовной концессией</a> в кинотеатр (самая быстрая скорость спавна).<br><br>Имейте в виду, что некоторые идентификаторы предметов <b>могут превышать лимит символов имени питомца</b>. В таких случаях вы можете использовать кнопку копирования, предоставленную этим инструментом, чтобы обойти лимит. Он работает, разбивая строки, чтобы поместить коды в ширину текстового поля Марни и удаляя переносы строк с помощью новой <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">команды диалога</a>.<br><br><b>Предупреждение: Используйте идентификаторы предметов ниже на свой страх и риск. Это может повлиять на ваш игровой опыт.',
    "ko-KR":
      '아이템 ID를 캐릭터 이름 뒤에 추가하여 NPC와 대화하거나, <b>마니에게서 애완동물을 사</b> 아 아이템 ID를 이름에 추가하여 아이템을 생성할 수 있습니다.<br><br>게임 초반에는 캐릭터 이름 생성을 쉽게 유발할 수 있습니다. <b>전화로 Gus와 대화</b>하면 (또는 12:00 이전에 Pierre와 대화) 영화관을 잠금 해제한 후 <b>Jodi를 <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a>로 영화관에 초대</b>하여 스폰 속도를 높일 수 있습니다.<br><br>특정 아이템 ID는 <b>애완동물 이름 문자 제한을 초과할 수 있습니다</b>. 이러한 경우에는 이 도구에서 제공하는 복사 버튼을 사용하여 제한을 우회할 수 있습니다. 이 버튼은 Marnie의 텍스트 상자 너비에 코드를 맞추기 위해 줄을 나누고 새로운 <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">대화 명령</a>을 사용하여 줄 바꿈을 제거합니다.<br><br><b>경고: 아래의 아이템 ID를 사용할 때는 자기 책임하에 사용하십시오. 이렇게 하면 게임 경험이 영향을 받을 수 있습니다.',
    "ja-JP":
      'アイテムIDをキャラクターの名前に追加してNPCに話しかけるか、<b>マーニーからペットを購入</b>してその名前にアイテムIDを追加することでアイテムを生成することができます。<br><br>ゲーム序盤では、キャラクターの名前スポーンを簡単にトリガーできます。<b>電話でガスと話す</b>（または12:00までにピエールと話す）ことで、映画館をアンロックした後、<b>ジョディを<a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">ラブコンセッション</a>で映画館に招待</b>することでスパムできます（最速のスポーンレート）。<br><br>特定のアイテムIDは<b>ペットの名前の文字制限を超える可能性があります</b>。そのような場合は、このツールが提供するコピー ボタンを使用して制限をバイパスできます。これは、コードをマーニーのテキストボックスの幅に合わせるために行を分割し、新しい<a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">ダイアログコマンド</a>を使用して改行を削除することで機能します。<br><br><b>警告: 以下のアイテムIDを使用する際は自己責任でご利用ください。これによりゲーム体験に影響を与える可能性があります。',
    "it-IT":
      'Puoi generare oggetti aggiungendo l\'ID dell\'oggetto al nome del tuo personaggio e poi parlando con gli NPC, o <b>comprando un animale da Marnie</b> aggiungendo l\'ID dell\'oggetto al suo nome.<br><br>All\'inizio del gioco puoi attivare facilmente la generazione del nome del personaggio parlando con Gus tramite <b>telefono</b> (o Pierre prima delle 12:00) e dopo aver sbloccato il cinema puoi spammare il tutto invitando Jodi con una <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> al cinema (velocità di generazione più veloce).<br><br>Tieni presente che certi ID degli oggetti <b>potrebbero superare il limite di caratteri del nome dell\'animale domestico</b>. In tali casi, puoi utilizzare il pulsante di copia fornito da questo strumento per aggirare il limite. Funziona suddividendo le righe per adattare i codici alla larghezza della casella di testo di Marnie e rimuovendo le interruzioni di riga utilizzando il nuovo <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">comando di dialogo</a>.<br><br><b>Avvertenza: Utilizza gli ID degli oggetti sottostanti a tuo rischio e pericolo. Farlo potrebbe influenzare la tua esperienza di gioco.',
    "hu-HU":
      'Elemeket hozhatsz létre az elemazonosító hozzáfűzésével a karakter nevéhez, majd NPC-kkel való beszélgetéssel, vagy <b>egy háziállat vásárlásával Marnie-től</b> az elemazonosító hozzáfűzésével a nevéhez.<br><br>A játék elején könnyen kiválthatod a karakter nevei generálását, <b>Gus-szal telefonon keresztül való beszélgetéssel</b> (vagy Pierre-rel 12:00 előtt) és a mozi feloldása után spamelheted, ha <b>Jodi-t meghívatod egy <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a>-nel a mozihoz</b> (a leggyorsabb generálási sebesség).<br><br>Figyelmeztetés: Bizonyos elemazonosítók <b>meghaladhatják a háziállat nevének karakterkorlátját</b>. Ilyen esetekben ezt az eszközt biztosító másolás gombbal kerülheted meg a korlátot. Úgy működik, hogy sorokra tördeli a kódokat, hogy beférjenek Marnie szövegdobozának szélességébe, és eltávolítja a sortöréseket az új <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">párbeszédparancs</a> használatával.<br><br><b>Figyelem: Az alábbi elemazonosítókat saját felelősségedre használd. Az ilyen használat befolyásolhatja a játékélményedet.',
    "fr-FR":
      "Vous pouvez faire apparaître des objets en ajoutant l'ID de l'objet au nom de votre personnage, puis en parlant aux PNJ, ou en <b>achetant un animal de compagnie à Marnie</b> en ajoutant l'ID de l'objet à son nom.<br><br>En début de partie, vous pouvez facilement déclencher l'apparition du nom du personnage en <b>parlant à Gus par téléphone</b> (ou Pierre avant 12h) et après avoir débloqué le cinéma, vous pouvez le spammer en <b>invitant Jodi avec une <a href=\"https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions\" target=\"_blank\">Love Concession</a> au cinéma</b> (taux d'apparition le plus rapide).<br><br>Soyez conscient que certains ID d'objets <b>peuvent dépasser la limite de caractères du nom de l'animal de compagnie</b>. Dans de tels cas, vous pouvez utiliser le bouton de copie fourni par cet outil pour contourner la limite. Il fonctionne en cassant les lignes pour adapter les codes à la largeur de la boîte de texte de Marnie et en supprimant les sauts de ligne à l'aide de la nouvelle <a href=\"https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female\" target=\"_blank\">commande de dialogue</a>.<br><br><b>Avertissement : Utilisez les ID d'objets ci-dessous à vos propres risques. Cela peut affecter votre expérience de jeu.",
    "es-ES":
      'Puedes generar objetos añadiendo el ID del objeto al nombre de tu personaje y luego hablando con los NPC, o <b>comprando una mascota a Marnie</b> añadiendo el ID del objeto a su nombre.<br><br>Al principio del juego puedes activar fácilmente la generación del nombre del personaje hablando con Gus a través del <b>teléfono</b> (o Pierre antes de las 12:00) y después de desbloquear el cine puedes spammearlo invitando a Jodi con una <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> al cine (la velocidad de generación más rápida).<br><br>Ten en cuenta que ciertos ID de objetos <b>pueden exceder el límite de caracteres del nombre de la mascota</b>. En tales casos, puedes utilizar el botón de copiar proporcionado por esta herramienta para evitar el límite. Funciona dividiendo las líneas para ajustar los códigos al ancho del cuadro de texto de Marnie y eliminando los saltos de línea mediante el nuevo <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">comando de diálogo</a>.<br><br><b>Advertencia: Utiliza los ID de objetos a continuación bajo tu propio riesgo. Hacerlo puede afectar tu experiencia de juego.',
    "de-DE":
      'Sie können Gegenstände erzeugen, indem Sie die Gegenstands-ID an den Namen Ihres Charakters anhängen und dann mit NPCs sprechen, oder indem Sie <b>ein Haustier von Marnie kaufen</b>, indem Sie die Gegenstands-ID an seinen Namen anhängen.<br><br>Am Anfang des Spiels können Sie den Charakternamens-Spawn leicht auslösen, indem Sie <b>mit Gus über das Telefon sprechen</b> (oder Pierre vor 12:00) und nach dem Freischalten des Kinos können Sie ihn spammen, indem Sie <b>Jodi mit einer <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> ins Kino einladen</b> (schnellste Spawnrate).<br><br>Beachten Sie, dass bestimmte Gegenstands-IDs <b>die Zeichenbegrenzung des Haustiernamens überschreiten können</b>. In solchen Fällen können Sie die vom Tool bereitgestellte Kopierfunktion verwenden, um die Begrenzung zu umgehen. Es funktioniert, indem es Zeilen bricht, um die Codes in die Breite des Textfelds von Marnie zu passen, und die Zeilenumbrüche mit dem neuen <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">Dialogbefehl</a> entfernt.<br><br><b>Warnung: Verwenden Sie die unten stehenden Gegenstands-IDs auf eigene Gefahr. Dies kann Ihre Spielerfahrung beeinträchtigen.',
    "tr-TR":
      'Öğeleri karakterinizin adına öğe kimliğini ekleyerek ve ardından NPC\'lere konuşarak veya <b>Marnie\'den bir evcil hayvan satın alarak</b> öğe kimliğini adına ekleyerek oluşturabilirsiniz.<br><br>Oyunun başında, karakter adı spawnlarını <b>telefonla Gus ile konuşarak</b> (veya 12:00\'den önce Pierre ile) kolayca tetikleyebilir ve sinemayı açtıktan sonra <b>Jodi\'yi <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> ile sinemaya davet ederek spamlayabilirsiniz</b> (en hızlı spawn oranı).<br><br>Bazı öğe kimlikleri <b>evcil hayvanın adı karakter sınırını aşabilir</b>. Bu tür durumlarda, bu sınırı atlamak için bu araç tarafından sağlanan kopyalama düğmesini kullanabilirsiniz. Kodları Marnie\'nin metin kutusu genişliğine sığdırmak için satırları kırarak ve yeni <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">diyalog komutu</a> kullanarak satır sonlarını kaldırarak çalışır.<br><br><b>Uyarı: Aşağıdaki öğe kimliklerini kendi sorumluluğunuzda kullanın. Bu, oyun deneyiminizi etkileyebilir.',
  },
  description2debug: {
    "en-US":
      'You can also spawn items using chat cheats. It\'s the <b>only option for mobile players</b> since breaking lines in Marnie doesn\'t work. To enable chat cheats in your save, please follow below instructions:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Locate your save file</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Edit the save file</a> (make a backup first)</li><li>Find the <code>&lt;allowChatCheats&gt;</code> element and change its value to <code>true</code><div class="action info inline readonly" id="debugFileInfo" data-text="If the option isn\'t available in your save file, ensure you have slept at least one day in version 1.6.9 or later."></div></li><li>Load the save normally</li></ol>With this mode enabled, you don\'t need to rename your pets or change your name using item codes. Simply copy the command from the icon below and paste it into the chat. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Mobile players</a></b>: tap the date in the top-right corner to open the chat) The item will then be spawned in your inventory.<br><br>There are <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">many debug commands available</a>, such as setting money, adjusting movement speed, warping to locations, and more.<br><br><b>Warning: Use the item IDs below at your own risk. Doing so may affect your gaming experience.</b>',
    "pt-BR":
      'Você também pode spawnar itens usando cheats no chat. É a <b>única opção para jogadores de celular</b> já que quebrar linhas na Marnie não funciona. Para habilitar cheats no chat no seu save, siga as instruções abaixo:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Localize seu arquivo de save</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Edite o arquivo de save</a> (faça um backup primeiro)</li><li>Encontre o elemento <code>&lt;allowChatCheats&gt;</code> e mude seu valor para <code>true</code><div class="action info inline readonly" id="debugFileInfo" data-text="Se a opção não estiver disponível no seu arquivo de save, certifique-se de ter dormido pelo menos um dia na versão 1.6.9 ou posterior."></div></li><li>Carregue o save normalmente</li></ol>Com esse modo habilitado, você não precisa renomear seus pets ou mudar seu nome usando códigos de item. Simplesmente copie o comando do ícone abaixo e cole no chat. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Jogadores de celular</a></b>: toque na data no canto superior direito para abrir o chat) O item será então spawnado no seu inventário.<br><br>Há <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">muitos comandos de debug disponíveis</a>, como definir dinheiro, ajustar a velocidade de movimento, teleportar para locais e mais.<br><br><b>Aviso: Use os IDs de item abaixo por sua própria conta e risco. Fazer isso pode afetar sua experiência de jogo.</b>',
    "ru-RU":
      'Вы также можете вызывать предметы, используя читы в чате. Это <b>единственный вариант для мобильных игроков</b>, поскольку разбивка строк в Марни не работает. Чтобы включить читы в чате в вашем сохранении, следуйте инструкциям ниже:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Найдите ваш файл сохранения</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Отредактируйте файл сохранения</a> (сначала сделайте резервную копию)</li><li>Найдите элемент <code>&lt;allowChatCheats&gt;</code> и измените его значение на <code>true</code><div class="action info inline readonly" id="debugFileInfo" data-text="Если опция недоступна в вашем файле сохранения, убедитесь, что вы спали хотя бы один день в версии 1.6.9 или более поздней."></div></li><li>Загрузите сохранение обычным образом</li></ol>При включенном этом режиме вам не нужно переименовывать своих питомцев или менять свое имя с помощью кодов предметов. Просто скопируйте команду из иконки ниже и вставьте ее в чат. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Мобильные игроки</a></b>: коснитесь даты в правом верхнем углу, чтобы открыть чат) Предмет затем появится в вашем инвентаре.<br><br>Доступно <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">много отладочных команд</a>, таких как установка денег, настройка скорости движения, телепортация в места и многое другое.<br><br><b>Предупреждение: Используйте идентификаторы предметов ниже на свой страх и риск. Это может повлиять на ваш игровой опыт.</b>',
    "ko-KR":
      '채팅 치트를 사용하여 아이템을 생성할 수도 있습니다. Marnie에서 줄 바꿈이 작동하지 않기 때문에 이것은 <b>모바일 플레이어의 유일한 옵션</b>입니다. 저장에서 채팅 치트를 활성화하려면 아래 지침을 따르십시오:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">저장 파일을 찾으세요</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">저장 파일을 편집하세요</a> (먼저 백업을 만드세요)</li><li><code>&lt;allowChatCheats&gt;</code> 요소를 찾아 값을 <code>true</code>로 변경하세요<div class="action info inline readonly" id="debugFileInfo" data-text="저장 파일에서 이 옵션이 사용할 수 없는 경우, 버전 1.6.9 이상에서 하루 이상 잤는지 확인하세요."></div></li><li>보통대로 저장을 불러오세요</li></ol>이 모드를 활성화하면 펫의 이름을 바꾸거나 아이템 코드를 사용하여 이름을 변경할 필요가 없습니다. 아래 아이콘에서 명령을 복사하여 채팅에 붙여넣기만 하면 됩니다. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">모바일 플레이어</a></b>: 오른쪽 상단의 날짜를 탭하여 채팅을 엽니다) 그러면 아이템이 인벤토리에 생성됩니다.<br><br>돈 설정, 이동 속도 조정, 위치로 이동하는 등 <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">많은 디버그 명령</a>이 있습니다.<br><br><b>경고: 아래의 아이템 ID를 사용할 때는 자기 책임하에 사용하십시오. 이렇게 하면 게임 경험이 영향을 받을 수 있습니다.</b>',
    "ja-JP":
      'チャットチートを使用してアイテムをスポーンすることもできます。これはMarnieで行を分割することができないため、<b>モバイルプレイヤーの唯一の選択肢</b>です。セーブでチャットチートを有効にするには、以下の手順に従ってください:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">セーブファイルを見つける</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">セーブファイルを編集する</a>（まずバックアップを作成してください）</li><li><code>&lt;allowChatCheats&gt;</code>要素を見つけ、その値を<code>true</code>に変更する<div class="action info inline readonly" id="debugFileInfo" data-text="セーブファイルでこのオプションが利用できない場合は、バージョン1.6.9以降で少なくとも1日寝たことを確認してください。"></div></li><li>通常通りセーブをロードする</li></ol>このモードを有効にすると、ペットの名前を変更したり、アイテムコードを使用して名前を変更する必要はありません。下のアイコンからコマンドをコピーしてチャットに貼り付けるだけで、アイテムがインベントリにスポーンされます。 (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">モバイルプレイヤー</a></b>: 右上の日付をタップしてチャットを開く) そのアイテムはあなたのインベントリにスポーンされます。<br><br>お金の設定、移動速度の調整、場所へのワープなど、<a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">多くのデバッグコマンド</a>が利用可能です。<br><br><b>警告: 以下のアイテムIDを使用する際は自己責任でご利用ください。これによりゲーム体験に影響を与える可能性があります。</b>',
    "it-IT":
      'Puoi anche generare oggetti utilizzando i trucchi della chat. È l\'<b>unica opzione per i giocatori mobili</b> poiché la rottura delle righe in Marnie non funziona. Per abilitare i trucchi della chat nel tuo salvataggio, segui le istruzioni seguenti:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Individua il tuo file di salvataggio</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Modifica il file di salvataggio</a> (fai prima un backup)</li><li>Trova l\'elemento <code>&lt;allowChatCheats&gt;</code> e cambia il suo valore in <code>true</code><div class="action info inline readonly" id="debugFileInfo" data-text="Se l\'opzione non è disponibile nel tuo file di salvataggio, assicurati di aver dormito almeno un giorno nella versione 1.6.9 o successiva."></div></li><li>Carica il salvataggio normalmente</li></ol>Con questa modalità abilitata, non è necessario rinominare i tuoi animali domestici o cambiare il tuo nome utilizzando i codici degli oggetti. Basta copiare il comando dall\'icona sottostante e incollarlo nella chat. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Giocatori mobili</a></b>: tocca la data nell\'angolo in alto a destra per aprire la chat) L\'oggetto verrà quindi generato nel tuo inventario.<br><br>Ci sono <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">molti comandi di debug disponibili</a>, come impostare i soldi, regolare la velocità di movimento, teletrasportarsi in luoghi e altro ancora.<br><br><b>Avvertenza: Utilizza gli ID degli oggetti sottostanti a tuo rischio e pericolo. Farlo potrebbe influenzare la tua esperienza di gioco.</b>',
    "hu-HU":
      'Az elemeket chat csalások segítségével is előhozhatod. Ez a <b>csak a mobil játékosok számára elérhető opció</b>, mivel a sorok törése Marnie-ban nem működik. A chat csalások engedélyezéséhez a mentésedben, kövesd az alábbi utasításokat:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Keresd meg a mentési fájlodat</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Szerkeszd meg a mentési fájlt</a> (készíts először egy biztonsági másolatot)</li><li>Keresd meg a <code>&lt;allowChatCheats&gt;</code> elemet, és változtasd meg az értékét <code>true</code>-ra<div class="action info inline readonly" id="debugFileInfo" data-text="Ha az opció nem elérhető a mentési fájlodban, győződj meg róla, hogy legalább egy napot aludtál a 1.6.9-es vagy újabb verzióban."></div></li><li>Töltsd be a mentést normál módon</li></ol>Ezzel a móddal nem kell átnevezned a háziállataidat vagy megváltoztatnod a nevedet az elemkódok használatával. Egyszerűen másold ki a parancsot az alábbi ikonról, majd illeszd be a chatbe. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Mobil játékosok</a></b>: koppints a jobb felső sarokban lévő dátumra a chat megnyitásához) Az elem ezután megjelenik az inventáriumodban.<br><br>Sok debug parancs áll rendelkezésre, például pénz beállítása, mozgási sebesség beállítása, helyekre ugrás és még sok más.<br><br><b>Figyelmeztetés: Az alábbi elemazonosítókat saját felelősségedre használd. Az ilyen használat befolyásolhatja a játékélményedet.</b>',
    "fr-FR":
      'Vous pouvez également faire apparaître des objets en utilisant des triches dans le chat. C\'est la <b>seule option pour les joueurs mobiles</b> car la rupture de lignes dans Marnie ne fonctionne pas. Pour activer les triches dans le chat dans votre sauvegarde, veuillez suivre les instructions ci-dessous:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Localisez votre fichier de sauvegarde</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Modifiez le fichier de sauvegarde</a> (faites d\'abord une sauvegarde)</li><li>Recherchez l\'élément <code>&lt;allowChatCheats&gt;</code> et changez sa valeur en <code>true</code><div class="action info inline readonly" id="debugFileInfo" data-text="Si l\'option n\'est pas disponible dans votre fichier de sauvegarde, assurez-vous d\'avoir dormi au moins un jour en version 1.6.9 ou ultérieure."></div></li><li>Chargez la sauvegarde normalement</li></ol>Avec ce mode activé, vous n\'avez pas besoin de renommer vos animaux de compagnie ou de changer votre nom en utilisant des codes d\'objet. Copiez simplement la commande de l\'icône ci-dessous et collez-la dans le chat. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Joueurs mobiles</a></b>: appuyez sur la date dans le coin supérieur droit pour ouvrir le chat) L\'objet apparaîtra alors dans votre inventaire.<br><br>Il existe de <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">nombreuses commandes de débogage disponibles</a>, telles que définir de l\'argent, ajuster la vitesse de déplacement, se téléporter vers des emplacements, et plus encore.<br><br><b>Avertissement : Utilisez les ID d\'objets ci-dessous à vos propres risques. Cela peut affecter votre expérience de jeu.</b>',
    "es-ES":
      'También puedes generar objetos usando trucos de chat. Es la <b>única opción para jugadores móviles</b> ya que romper líneas en Marnie no funciona. Para habilitar los trucos de chat en tu partida, sigue las instrucciones a continuación:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Localiza tu archivo de guardado</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Edita el archivo de guardado</a> (haz una copia de seguridad primero)</li><li>Encuentra el elemento <code>&lt;allowChatCheats&gt;</code> y cambia su valor a <code>true</code><div class="action info inline readonly" id="debugFileInfo" data-text="Si la opción no está disponible en tu archivo de guardado, asegúrate de haber dormido al menos un día en la versión 1.6.9 o posterior."></div></li><li>Carga la partida normalmente</li></ol>Con este modo habilitado, no necesitas renombrar a tus mascotas o cambiar tu nombre usando códigos de objetos. Simplemente copia el comando del icono de abajo y pégalo en el chat. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Jugadores móviles</a></b>: toca la fecha en la esquina superior derecha para abrir el chat) El objeto aparecerá en tu inventario.<br><br>Hay <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">muchos comandos de depuración disponibles</a>, como establecer dinero, ajustar la velocidad de movimiento, teletransportarse a ubicaciones y más.<br><br><b>Advertencia: Utiliza los ID de objetos a continuación bajo tu propio riesgo. Hacerlo puede afectar tu experiencia de juego.</b>',
    "de-DE":
      'Sie können auch Gegenstände mit Chat-Cheats erzeugen. Es ist die <b>einzige Option für mobile Spieler</b>, da das Zeilenumbruch in Marnie nicht funktioniert. Um Chat-Cheats in Ihrem Speicher zu aktivieren, befolgen Sie bitte die folgenden Anweisungen:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Suchen Sie Ihre Speicherdatei</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Bearbeiten Sie die Speicherdatei</a> (machen Sie zuerst ein Backup)</li><li>Finden Sie das Element <code>&lt;allowChatCheats&gt;</code> und ändern Sie seinen Wert in <code>true</code><div class="action info inline readonly" id="debugFileInfo" data-text="Wenn die Option in Ihrer Speicherdatei nicht verfügbar ist, stellen Sie sicher, dass Sie mindestens einen Tag in Version 1.6.9 oder höher geschlafen haben."></div></li><li>Laden Sie den Speicher normal</li></ol>Mit diesem Modus aktiviert, müssen Sie Ihre Haustiere nicht umbenennen oder Ihren Namen mit Hilfe von Gegenstandscodes ändern. Kopieren Sie einfach den Befehl aus dem untenstehenden Symbol und fügen Sie ihn in den Chat ein. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Mobile Spieler</a></b>: Tippen Sie auf das Datum in der oberen rechten Ecke, um den Chat zu öffnen) Der Gegenstand wird dann in Ihrem Inventar erscheinen.<br><br>Es gibt <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">viele Debug-Befehle verfügbar</a>, wie das Einstellen von Geld, das Anpassen der Bewegungsgeschwindigkeit, das Warpen zu Orten und mehr.<br><br><b>Warnung: Verwenden Sie die unten stehenden Gegenstands-IDs auf eigene Gefahr. Dies kann Ihre Spielerfahrung beeinträchtigen.</b>',
    "tr-TR":
      'Ayrıca sohbet hileleri kullanarak öğeleri oluşturabilirsiniz. Marnie\'de satırları kırmak çalışmadığından bu, <b>mobil oyuncular için tek seçenektir</b>. Kaydınızda sohbet hilelerini etkinleştirmek için lütfen aşağıdaki talimatları izleyin:<ol><li> <a href="https://stardewvalleywiki.com/Saves#Find_your_save_files" rel="noopener" target="_blank">Kayıt dosyanızı bulun</a></li><li><a href="https://stardewvalleywiki.com/Saves#Edit_a_save" rel="noopener" target="_blank">Kayıt dosyasını düzenleyin</a> (önce bir yedek alın)</li><li><code>&lt;allowChatCheats&gt;</code> öğesini bulun ve değerini <code>true</code> olarak değiştirin<div class="action info inline readonly" id="debugFileInfo" data-text="Seçenek kayıt dosyanızda mevcut değilse, en azından 1.6.9 sürümünde bir gün uyuduğunuzdan emin olun."></div></li><li>Kaydı normal şekilde yükleyin</li></ol>Bu mod etkinleştirildiğinde, evcil hayvanlarınızın adını değiştirmenize veya öğe kodlarını kullanarak adınızı değiştirmenize gerek yoktur. Aşağıdaki simgeden komutu kopyalayıp sohbete yapıştırmanız yeterlidir. (<b><a href="https://github.com/MateusAquino/stardewids/issues/1#issuecomment-2483640084" rel="noopener" target="_blank">Mobil oyuncular</a></b>: sohbeti açmak için sağ üst köşedeki tarihe dokunun) Öğe daha sonra envanterinize oluşturulacaktır.<br><br>Para ayarlama, hareket hızını ayarlama, konumlara sıçrama ve daha fazlası gibi <a href="https://stardewvalleywiki.com/Modding:Console_commands#Debug_commands" rel="noopener" target="_blank">birçok hata ayıklama komutu</a> mevcuttur.<br><br><b>Uyarı: Aşağıdaki öğe kimliklerini kendi sorumluluğunuzda kullanın. Bu, oyun deneyiminizi etkileyebilir.</b>',
  },
  free: {
    "en-US": "Free",
    "pt-BR": "Livre",
    "ru-RU": "Свободный",
    "ko-KR": "자유롭게",
    "ja-JP": "無料",
    "it-IT": "Libero",
    "hu-HU": "Ingyenes",
    "fr-FR": "Libre",
    "es-ES": "Gratis",
    "de-DE": "Frei",
    "tr-TR": "Ücretsiz",
  },
  cancel: {
    "en-US": "Cancel",
    "pt-BR": "Cancelar",
    "ru-RU": "Отмена",
    "ko-KR": "취소",
    "ja-JP": "キャンセル",
    "it-IT": "Annulla",
    "hu-HU": "Mégse",
    "fr-FR": "Annuler",
    "es-ES": "Cancelar",
    "de-DE": "Stornieren",
    "tr-TR": "İptal",
  },
  "free-description": {
    "en-US": `This is an advanced section where you can freely type any content to be escaped into Marnie's dialogue box. This includes some <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">dialogue commands</a> and  <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">trigger actions</a>.`,
    "pt-BR": `Esta é uma seção avançada onde você pode digitar livremente qualquer conteúdo a ser escapado na caixa de diálogo da Marnie. Isso inclui alguns <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">comandos de diálogo</a> e <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">ações de gatilho</a>.`,
    "ru-RU": `Это раздел для продвинутых, где вы можете свободно вводить любое содержимое для экранирования в текстовое поле диалога Марни. Сюда входят некоторые <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">команды диалога</a> и <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">действия триггера</a>.`,
    "ko-KR": `이 곳은 Marnie의 대화 상자에 이스케이프될 내용을 자유롭게 입력할 수 있는 고급 섹션입니다. 이에는 일부 <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">대화 명령</a> 및 <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">트리거 작업</a>이 포함됩니다.`,
    "ja-JP": `これは、Marnieのダイアログボックスにエスケープされる任意のコンテンツを自由に入力できる高度なセクションです。これにはいくつかの<a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">ダイアログコマンド</a>や<a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">トリガーアクション</a>が含まれます。`,
    "it-IT": `Questa è una sezione avanzata in cui puoi digitare liberamente qualsiasi contenuto da inserire nella casella di dialogo di Marnie. Questo include alcuni <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">comandi di dialogo</a> e <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">azioni di trigger</a>.`,
    "hu-HU": `Ez egy haladó szakasz, ahol szabadon beírhatsz bármilyen tartalmat, hogy Marnie párbeszédablakába kerüljön. Ez magában foglal néhány <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">párbeszédparancsot</a> és <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">trigger műveleteket</a>.`,
    "fr-FR": `Ceci est une section avancée où vous pouvez taper librement n'importe quel contenu à échapper dans la boîte de dialogue de Marnie. Cela inclut certaines <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">commandes de dialogue</a> et <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">actions de déclenchement</a>.`,
    "es-ES": `Esta es una sección avanzada donde puedes escribir libremente cualquier contenido para escapar en el cuadro de diálogo de Marnie. Esto incluye algunos <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">comandos de diálogo</a> y <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">acciones de desencadenador</a>.`,
    "de-DE": `Dies ist ein fortgeschrittener Abschnitt, in dem Sie beliebige Inhalte eingeben können, die in Marnies Dialogfeld entkommen sollen. Dies umfasst einige <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">Dialogbefehle</a> und <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">Triggeraktionen</a>.`,
    "tr-TR": `Bu, Marnie'nin diyalog kutusuna kaçırılacak herhangi bir içeriği serbestçe yazabileceğiniz gelişmiş bir bölümdür. Bu, bazı <a href="https://stardewvalleywiki.com/Modding:Dialogue" rel="noopener" target="_blank">diyalog komutları</a> ve <a href="https://stardewvalleywiki.com/Modding:Trigger_actions" rel="noopener" target="_blank">tetikleyici eylemleri</a> içerir.`,
  },
  "modal-description": {
    "en-US": "Type the number of items you want to copy:",
    "pt-BR": "Digite o número de itens que deseja copiar:",
    "ru-RU": "Введите количество копируемых предметов:",
    "ko-KR": "복사할 항목 수를 입력하십시오:",
    "ja-JP": "コピーするアイテムの数を入力してください：",
    "it-IT": "Digita il numero di elementi che desideri copiare:",
    "hu-HU": "Írd be az átmásolandó elemek számát:",
    "fr-FR": "Tapez le nombre d'éléments que vous souhaitez copier :",
    "es-ES": "Escribe el número de elementos que deseas copiar:",
    "de-DE": "Geben Sie die Anzahl der zu kopierenden Elemente ein:",
    "tr-TR": "Kopyalamak istediğiniz öğe sayısını yazın:",
  },
  pastemode: {
    "en-US": "Paste as:",
    "pt-BR": "Colar como:",
    "ru-RU": "Вставить как:",
    "ko-KR": "붙여넣기:",
    "ja-JP": "ペースト形式：",
    "it-IT": "Incolla come:",
    "hu-HU": "Beillesztés mint:",
    "fr-FR": "Coller comme :",
    "es-ES": "Pegar como:",
    "de-DE": "Einfügen als:",
    "tr-TR": "Yapıştırma şekli:",
  },
  chickenName: {
    "en-US": "Chicken Name",
    "pt-BR": "Nome da Galinha",
    "ru-RU": "Имя курицы",
    "ko-KR": "닭 이름",
    "ja-JP": "ニワトリの名前",
    "it-IT": "Nome del Pollo",
    "hu-HU": "Csirke neve",
    "fr-FR": "Nom du Poulet",
    "es-ES": "Nombre del Pollo",
    "de-DE": "Hühnernamen",
    "tr-TR": "Tavuk Adı",
  },
  playerName: {
    "en-US": "Player Name",
    "pt-BR": "Nome do Jogador",
    "ru-RU": "Имя игрока",
    "ko-KR": "플레이어 이름",
    "ja-JP": "プレイヤー名",
    "it-IT": "Nome del Giocatore",
    "hu-HU": "Játékos neve",
    "fr-FR": "Nom du Joueur",
    "es-ES": "Nombre del Jugador",
    "de-DE": "Spielername",
    "tr-TR": "Oyuncu Adı",
  },
  quality: {
    "en-US": "Quality:",
    "pt-BR": "Qualidade:",
    "ru-RU": "Качество:",
    "ko-KR": "품질:",
    "ja-JP": "品質：",
    "it-IT": "Qualità:",
    "hu-HU": "Minőség:",
    "fr-FR": "Qualité :",
    "es-ES": "Calidad:",
    "de-DE": "Qualität:",
    "tr-TR": "Kalite:",
  },
  default: {
    "en-US": "Default",
    "pt-BR": "Padrão",
    "ru-RU": "По умолчанию",
    "ko-KR": "기본값",
    "ja-JP": "デフォルト",
    "it-IT": "Predefinito",
    "hu-HU": "Alapértelmezett",
    "fr-FR": "Défaut",
    "es-ES": "Predeterminado",
    "de-DE": "Standard",
    "tr-TR": "Varsayılan",
  },
  silver: {
    "en-US": "Silver",
    "pt-BR": "Prata",
    "ru-RU": "Серебро",
    "ko-KR": "실버",
    "ja-JP": "シルバー",
    "it-IT": "Argento",
    "hu-HU": "Ezüst",
    "fr-FR": "Argent",
    "es-ES": "Plata",
    "de-DE": "Silber",
    "tr-TR": "Gümüş",
  },
  gold: {
    "en-US": "Gold",
    "pt-BR": "Ouro",
    "ru-RU": "Золото",
    "ko-KR": "골드",
    "ja-JP": "ゴールド",
    "it-IT": "Oro",
    "hu-HU": "Arany",
    "fr-FR": "Or",
    "es-ES": "Oro",
    "de-DE": "Gold",
    "tr-TR": "Altın",
  },
  iridium: {
    "en-US": "Iridium",
    "pt-BR": "Iridium",
    "ru-RU": "Иридий",
    "ko-KR": "이리듐",
    "ja-JP": "イリジウム",
    "it-IT": "Iridio",
    "hu-HU": "Iridium",
    "fr-FR": "Iridium",
    "es-ES": "Iridio",
    "de-DE": "Iridium",
    "tr-TR": "İridyum",
  },

  "category-Litter": {
    "en-US": "Litter",
    "pt-BR": "Lixo",
    "ru-RU": "Мусор",
    "ko-KR": "쓰레기",
    "ja-JP": "ゴミ",
    "it-IT": "Spazzatura",
    "hu-HU": "Szemét",
    "fr-FR": "Déchets",
    "es-ES": "Basura",
    "de-DE": "Abfall",
    "tr-TR": "Çöp",
  },
  "category-Basic": {
    "en-US": "Basic",
    "pt-BR": "Básico",
    "ru-RU": "Основной",
    "ko-KR": "기본",
    "ja-JP": "基本",
    "it-IT": "Base",
    "hu-HU": "Alap",
    "fr-FR": "De base",
    "es-ES": "Básico",
    "de-DE": "Grundlegend",
    "tr-TR": "Temel",
  },
  "category-Minerals": {
    "en-US": "Minerals",
    "pt-BR": "Minerais",
    "ru-RU": "Минералы",
    "ko-KR": "광물",
    "ja-JP": "鉱物",
    "it-IT": "Minerali",
    "hu-HU": "Ásványok",
    "fr-FR": "Minéraux",
    "es-ES": "Minerales",
    "de-DE": "Mineralien",
    "tr-TR": "Mineraller",
  },
  "category-Quest": {
    "en-US": "Quest",
    "pt-BR": "Missão",
    "ru-RU": "Задание",
    "ko-KR": "퀘스트",
    "ja-JP": "クエスト",
    "it-IT": "Missione",
    "hu-HU": "Küldetés",
    "fr-FR": "Quête",
    "es-ES": "Misión",
    "de-DE": "Quest",
    "tr-TR": "Görev",
  },
  "category-Crafting": {
    "en-US": "Crafting",
    "pt-BR": "Criação",
    "ru-RU": "Ремесло",
    "ko-KR": "제작",
    "ja-JP": "クラフト",
    "it-IT": "Artigianato",
    "hu-HU": "Készítés",
    "fr-FR": "Artisanat",
    "es-ES": "Creación",
    "de-DE": "Handwerk",
    "tr-TR": "El işi",
  },
  "category-Arch": {
    "en-US": "Arch",
    "pt-BR": "Arco",
    "ru-RU": "Арка",
    "ko-KR": "아치",
    "ja-JP": "アーチ",
    "it-IT": "Arco",
    "hu-HU": "Ív",
    "fr-FR": "Arc",
    "es-ES": "Arco",
    "de-DE": "Bogen",
    "tr-TR": "Kemer",
  },
  "category-Fish": {
    "en-US": "Fish",
    "pt-BR": "Peixe",
    "ru-RU": "Рыба",
    "ko-KR": "물고기",
    "ja-JP": "魚",
    "it-IT": "Pesce",
    "hu-HU": "Hal",
    "fr-FR": "Poisson",
    "es-ES": "Pescado",
    "de-DE": "Fisch",
    "tr-TR": "Balık",
  },
  "category-Cooking": {
    "en-US": "Cooking",
    "pt-BR": "Cozinha",
    "ru-RU": "Кулинария",
    "ko-KR": "요리",
    "ja-JP": "料理",
    "it-IT": "Cucina",
    "hu-HU": "Főzés",
    "fr-FR": "Cuisine",
    "es-ES": "Cocina",
    "de-DE": "Kochen",
    "tr-TR": "Yemek pişirme",
  },
  "category-Seeds": {
    "en-US": "Seeds",
    "pt-BR": "Sementes",
    "ru-RU": "Семена",
    "ko-KR": "씨앗",
    "ja-JP": "種",
    "it-IT": "Semi",
    "hu-HU": "Magok",
    "fr-FR": "Graines",
    "es-ES": "Semillas",
    "de-DE": "Samen",
    "tr-TR": "Tohumlar",
  },
  "category-Ring": {
    "en-US": "Ring",
    "pt-BR": "Anel",
    "ru-RU": "Кольцо",
    "ko-KR": "반지",
    "ja-JP": "リング",
    "it-IT": "Anello",
    "hu-HU": "Gyűrű",
    "fr-FR": "Anneau",
    "es-ES": "Anillo",
    "de-DE": "Ring",
    "tr-TR": "Yüzük",
  },
  "category-asdf": {
    "en-US": "Misc",
    "pt-BR": "Diversos",
    "ru-RU": "Разное",
    "ko-KR": "기타",
    "ja-JP": "その他",
    "it-IT": "Varie",
    "hu-HU": "Vegyes",
    "fr-FR": "Divers",
    "es-ES": "Varios",
    "de-DE": "Verschiedenes",
    "tr-TR": "Çeşitli",
  },
  "category-$All": {
    "en-US": "All",
    "pt-BR": "Todos",
    "ru-RU": "Все",
    "ko-KR": "모두",
    "ja-JP": "すべて",
    "it-IT": "Tutti",
    "hu-HU": "Összes",
    "fr-FR": "Tous",
    "es-ES": "Todos",
    "de-DE": "Alle",
    "tr-TR": "Hepsi",
  },
  "chat-cheats": {
    "en-US": "Chat Cheats",
    "pt-BR": "Trapaças de Chat",
    "ru-RU": "Читы в чате",
    "ko-KR": "채팅 치트",
    "ja-JP": "チャットチート",
    "it-IT": "Trucchi Chat",
    "hu-HU": "Csevegési Csak",
    "fr-FR": "Triche de Chat",
    "es-ES": "Trucos de Chat",
    "de-DE": "Chat-Cheats",
    "tr-TR": "Sohbet Hileleri",
  },
};
