const Strings = {
  copy: {
    "en-US": "Copy",
    "pt-BR": "Copiar",
    "ru-RU": "копия",
    "ko-KR": "부",
    "ja-JP": "コピー",
    "it-IT": "Copia",
    "hu-HU": "Másol",
    "fr-FR": "Copie",
    "es-ES": "Copia",
    "de-DE": "Kopieren",
    "tr-TR": "Kopyala",
  },
  copyN: {
    "en-US": "Copy many",
    "pt-BR": "Copiar vários",
    "ru-RU": "Копировать много",
    "ko-KR": "많은 복사",
    "ja-JP": "多数のコピー",
    "it-IT": "Copia molti",
    "hu-HU": "Sok másolat",
    "fr-FR": "Copier beaucoup",
    "es-ES": "Copia muchos",
    "de-DE": "Viele kopieren",
    "tr-TR": "Çok kopyala",
  },
  batch: {
    "en-US": "Batch copy",
    "pt-BR": "Copiar em lote",
    "ru-RU": "Пакетное копирование",
    "ko-KR": "일괄 복사",
    "ja-JP": "バッチコピー",
    "it-IT": "Copia batch",
    "hu-HU": "Tömegmásolás",
    "fr-FR": "Copie en lot",
    "es-ES": "Copia en bloque",
    "de-DE": "Stapelkopie",
    "tr-TR": "Toplu kopyala",
  },
  image: {
    "en-US": "Image",
    "pt-BR": "Imagem",
    "ru-RU": "Изображение",
    "ko-KR": "영상",
    "ja-JP": "画像",
    "it-IT": "Immagine",
    "hu-HU": "Kép",
    "fr-FR": "Image",
    "es-ES": "Imagen",
    "de-DE": "Bild",
    "tr-TR": "Resim",
  },
  item: {
    "en-US": "Item",
    "pt-BR": "Item",
    "ru-RU": "Пункт",
    "ko-KR": "항목",
    "ja-JP": "項目",
    "it-IT": "Articolo",
    "hu-HU": "Elem",
    "fr-FR": "Article",
    "es-ES": "Artículo",
    "de-DE": "Artikel",
    "tr-TR": "Öğe",
  },
  actions: {
    "en-US": "Actions",
    "pt-BR": "Ações",
    "ru-RU": "Действия",
    "ko-KR": "행동",
    "ja-JP": "アクション",
    "it-IT": "Azioni",
    "hu-HU": "Cselekvések",
    "fr-FR": "Actions",
    "es-ES": "Acciones",
    "de-DE": "Aktionen",
    "tr-TR": "Eylemler",
  },
  description1: {
    "en-US":
      "Tool developed by <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> to help you find the IDs of items in Stardew Valley <b>updated for the 1.6 update</b>.",
    "pt-BR":
      "Ferramenta desenvolvida por <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> para ajudar você a encontrar os IDs dos itens em Stardew Valley <b>atualizada para a versão 1.6</b>.",
    "ru-RU":
      "Инструмент, разработанный <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a>, чтобы помочь вам найти идентификаторы предметов в Stardew Valley <b>обновлено для обновления 1.6</b>.",
    "ko-KR":
      "<a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a>가 개발한 도구로, 스타듀 밸리의 항목 ID를 찾는 데 도움이 됩니다 <b>1.6 업데이트에 대한 업데이트</b>.",
    "ja-JP":
      "<a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a>によって開発されたツールで、Stardew ValleyのアイテムのIDを見つけるのに役立ちます <b>1.6アップデート用に更新</b>.",
    "it-IT":
      "Strumento sviluppato da <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> per aiutarti a trovare gli ID degli oggetti in Stardew Valley <b>aggiornato per l'aggiornamento 1.6</b>.",
    "hu-HU":
      "<a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> által kifejlesztett eszköz, amely segít megtalálni a Stardew Valley elemek azonosítóit <b>frissítve a 1.6 frissítéshez</b>.",
    "fr-FR":
      "Outil développé par <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> pour vous aider à trouver les identifiants des éléments dans Stardew Valley <b>mis à jour pour la mise à jour 1.6</b>.",
    "es-ES":
      "Herramienta desarrollada por <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> para ayudarte a encontrar los IDs de los objetos en Stardew Valley <b>actualizado para la actualización 1.6</b>.",
    "de-DE":
      "Tool entwickelt von <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a>, um Ihnen zu helfen, die IDs von Gegenständen in Stardew Valley zu finden <b>aktualisiert für das 1.6-Update</b>.",
    "tr-TR":
      "Stardew Valley'deki öğelerin kimliklerini bulmanıza yardımcı olmak için <a href='https://github.com/MateusAquino/stardewids' target='_blank'>Mateus Aquino</a> tarafından geliştirilen araç <b>1.6 güncellemesi için güncellendi</b>.",
  },
  spawn: {
    "en-US": "Spawning items",
    "pt-BR": "Spawnando itens",
    "ru-RU": "Появление предметов",
    "ko-KR": "아이템 생성",
    "ja-JP": "アイテムの生成",
    "it-IT": "Generazione di oggetti",
    "hu-HU": "Elemek előhozása",
    "fr-FR": "Apparition d'objets",
    "es-ES": "Aparición de objetos",
    "de-DE": "Gegenstände erscheinen",
    "tr-TR": "Öğeleri doğurmak",
  },
  description2: {
    "en-US":
      'You can spawn items by appending the item ID to your character\'s name and then talking to NPCs, or by <b>buying a pet from Marnie</b> appending the item ID to its name.<br><br>During early game you can easily trigger character\'s name spawns by <b> talking to Gus via phone</b> (or Pierre before 12:00) and after unlocking the cinema you can spam it by<b> inviting Jodi with a <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> to the movie theater</b> (fastest spawn rate).<br><br>Be aware that certain item IDs <b>may exceed the pet\'s name character limit</b>. In such instances, you can use the copy button provided by this tool to bypass the limit. It works by breaking lines to fit the width of the text box using the new <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">dialogue command</a> to erase the break line character inside a dialogue box.<br><br><b>Warning: Use the item IDs below at your own risk. Doing so may affect your gaming experience.',
    "pt-BR":
      'Você pode spawnar itens adicionando o ID do item ao nome do seu personagem e então falando com NPCs, ou <b>comprando um pet da Marnie</b> adicionando o ID do item ao nome dele.<br><br>No início do jogo você pode facilmente spawnar itens com o nome do personagem falando com o Gus pelo <b>telefone</b> (ou com o Pierre antes das 12:00) e após desbloquear o cinema você pode spammar o spawn de itens convidando a Jodi com um <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> para o cinema (maior taxa de spawn).<br><br>Tenha em mente que certos IDs de item <b>podem exceder o limite de caracteres do nome do pet</b>. Em tais casos, você pode usar o botão de copiar fornecido por esta ferramenta para burlar o limite. Ele funciona quebrando linhas para caber na largura da caixa de texto usando o novo <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">comando de diálogo</a> para apagar o caractere de quebra de linha dentro de uma caixa de diálogo.<br><br><b>Aviso: Use os IDs de item abaixo por sua própria conta e risco. Fazer isso pode afetar sua experiência de jogo.',
    "ru-RU":
      'Вы можете создавать предметы, добавляя идентификатор предмета к имени своего персонажа, а затем разговаривая с NPC, или <b>покупая питомца у Марни</b>, добавляя идентификатор предмета к его имени.<br><br>В начале игры вы можете легко вызвать появление имени персонажа, <b>поговорив с Гасом по телефону</b> (или с Пьером до 12:00), и после разблокировки кинотеатра вы можете спамить это, пригласив Джоди с <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> в кинотеатр (самая быстрая скорость появления).<br><br>Имейте в виду, что некоторые идентификаторы предметов <b>могут превышать лимит символов имени питомца</b>. В таких случаях вы можете использовать кнопку копирования, предоставленную этим инструментом, чтобы обойти лимит. Он работает, разбивая строки, чтобы они вписывались в ширину текстового поля с использованием новой <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">команды диалога</a> для стирания символа разрыва строки внутри диалогового окна.<br><br><b>Предупреждение: Используйте идентификаторы предметов ниже на свой страх и риск. Это может повлиять на ваш игровой опыт.',
    "ko-KR":
      '아이템 ID를 캐릭터 이름에 추가한 다음 NPC와 대화하거나, <b>마니에게 애완동물을 사서</b> 해당 아이템 ID를 이름에 추가하여 아이템을 생성할 수 있습니다.<br><br>게임 초반에는 <b>전화로 구스와 대화</b> (또는 12:00 이전에 피에르와 대화)하여 캐릭터 이름 생성을 쉽게 트리거할 수 있으며, 영화관을 잠금 해제한 후에는 <b>영화관에 <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a>로 조디를 초대하여</b> 이를 스팸할 수 있습니다 (최대 생성률).<br><br>특정 아이템 ID는 <b>애완동물 이름 문자 제한을 초과할 수 있습니다</b>. 이러한 경우, 이 도구에서 제공하는 복사 버튼을 사용하여 제한을 우회할 수 있습니다. 이 버튼은 대화 상자 내부의 줄 바꿈 문자를 지우는 새로운 <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">대화 명령</a>을 사용하여 텍스트 상자의 너비에 맞게 줄을 나누어 작동합니다.<br><br><b>경고: 아래의 아이템 ID를 사용하는 것은 본인 책임입니다. 이렇게 하면 게임 경험이 영향을 받을 수 있습니다.',
    "ja-JP":
      'アイテムIDをキャラクターの名前に追加してNPCに話しかけるか、<b>マーニーからペットを購入</b>してその名前にアイテムIDを追加することでアイテムを生成できます。<br><br>ゲーム序盤では、<b>電話でグスと話す</b>（または12:00までにピエールと話す）ことで簡単にキャラクター名のスポーンをトリガーでき、映画館を解除した後は、<b>映画館に<a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">ラブコンセッション</a>でジョディを招待して</b> これをスパムできます（最速のスポーン率）。<br><br>特定のアイテムIDは<b>ペットの名前の文字制限を超える可能性があります</b>。 そのような場合は、このツールが提供するコピー ボタンを使用して制限をバイパスできます。 これは、新しい<a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">ダイアログ コマンド</a>を使用して、ダイアログ ボックス内の改行文字を消去して、テキスト ボックスの幅に合わせて行を分割することで機能します。<br><br><b>警告: 以下のアイテムIDを使用する場合は自己責任でお願いします。 これを行うとゲーム体験に影響を与える可能性があります。',
    "it-IT":
      'Puoi generare oggetti aggiungendo l\'ID dell\'oggetto al nome del tuo personaggio e poi parlando con gli NPC, o <b>comprando un animale da Marnie</b> aggiungendo l\'ID dell\'oggetto al suo nome.<br><br>All\'inizio del gioco puoi attivare facilmente i nomi dei personaggi parlando con Gus tramite <b>telefono</b> (o con Pierre prima delle 12:00) e dopo aver sbloccato il cinema puoi spammarlo invitando Jodi con un <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> al cinema (velocità di spawn più veloce).<br><br>Tieni presente che alcuni ID degli oggetti <b>potrebbero superare il limite di caratteri del nome dell\'animale domestico</b>. In tali casi, puoi utilizzare il pulsante di copia fornito da questo strumento per aggirare il limite. Funziona suddividendo le righe per adattarle alla larghezza della casella di testo utilizzando il nuovo <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">comando di dialogo</a> per cancellare il carattere di interruzione della riga all\'interno di una casella di dialogo.<br><br><b>Avviso: Utilizza i seguenti ID degli oggetti a tuo rischio e pericolo. Farlo potrebbe influenzare la tua esperienza di gioco.',
    "hu-HU":
      'Az elemeket hozzáadhatja a karakter nevéhez az elem azonosítójának hozzáfűzésével, majd beszélgethet az NPC-vel, vagy <b>vásárolhat egy háziállatot Marnie-tól</b>, az elem azonosítójának hozzáfűzésével a nevéhez.<br><br>A játék elején könnyen aktiválhatja a karakter nevek megjelenítését, ha <b>beszél Gus-szal telefonon</b> (vagy Pierre-rel 12:00 előtt), és miután feloldotta a mozit, spamelheti, ha meghívja Jodi-t egy <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> a moziba (leggyorsabb megjelenítési arány).<br><br>Vegye figyelembe, hogy egyes elemazonosítók <b>meghaladhatják a háziállat nevének karakterkorlátját</b>. Ilyen esetekben használhatja ezt az eszközt biztosító másolás gombot a korlát megkerülésére. Úgy működik, hogy sorokra bontja, hogy beférjen a szövegdoboz szélességébe, a szövegdobozban a sorváltó karakter törlésével az új <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">párbeszédparancs</a> használatával.<br><br><b>Figyelem: Az alábbi elemazonosítókat saját felelősségére használja. Ennek következtében befolyásolhatja a játékélményét.',
    "fr-FR":
      "Vous pouvez faire apparaître des objets en ajoutant l'ID de l'objet au nom de votre personnage, puis en parlant aux PNJ, ou en <b>achetant un animal de compagnie à Marnie</b> en ajoutant l'ID de l'objet à son nom.<br><br>En début de partie, vous pouvez facilement déclencher les noms de personnages en <b>parlant à Gus par téléphone</b> (ou à Pierre avant 12h) et après avoir débloqué le cinéma, vous pouvez le spammer en <b>invitant Jodi avec une <a href=\"https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions\" target=\"_blank\">Love Concession</a> au cinéma</b> (taux d'apparition le plus rapide).<br><br>Soyez conscient que certains ID d'objets <b>peuvent dépasser la limite de caractères du nom de l'animal de compagnie</b>. Dans de tels cas, vous pouvez utiliser le bouton de copie fourni par cet outil pour contourner la limite. Il fonctionne en cassant les lignes pour s'adapter à la largeur de la zone de texte en utilisant la nouvelle <a href=\"https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female\" target=\"_blank\">commande de dialogue</a> pour effacer le caractère de saut de ligne à l'intérieur d'une boîte de dialogue.<br><br><b>Avertissement : Utilisez les ID d'objets ci-dessous à vos propres risques. Cela pourrait affecter votre expérience de jeu.",
    "es-ES":
      'Puedes generar objetos añadiendo el ID del objeto al nombre de tu personaje y luego hablando con los NPC, o <b>comprando una mascota a Marnie</b> añadiendo el ID del objeto a su nombre.<br><br>Al principio del juego puedes activar fácilmente los nombres de los personajes hablando con Gus por <b>teléfono</b> (o con Pierre antes de las 12:00) y después de desbloquear el cine puedes hacer spam invitando a Jodi con una <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> al cine (la tasa de aparición más rápida).<br><br>Ten en cuenta que ciertos ID de objetos <b>pueden exceder el límite de caracteres del nombre de la mascota</b>. En tales casos, puedes usar el botón de copiar proporcionado por esta herramienta para evitar el límite. Funciona dividiendo las líneas para que se ajusten al ancho del cuadro de texto utilizando el nuevo <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">comando de diálogo</a> para borrar el carácter de salto de línea dentro de un cuadro de diálogo.<br><br><b>Advertencia: Utiliza los ID de objetos a continuación bajo tu propio riesgo. Hacerlo puede afectar tu experiencia de juego.',
    "de-DE":
      'Sie können Gegenstände erzeugen, indem Sie die ID des Gegenstands an den Namen Ihres Charakters anhängen und dann mit NPCs sprechen oder <b>ein Haustier von Marnie kaufen</b>, indem Sie die ID des Gegenstands an seinen Namen anhängen.<br><br>Am Anfang des Spiels können Sie den Namen des Charakters leicht auslösen, indem Sie mit Gus über das <b>Telefon sprechen</b> (oder mit Pierre vor 12:00 Uhr) und nachdem Sie das Kino freigeschaltet haben, können Sie es spammen, indem Sie Jodi mit einem <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> ins Kino einladen (schnellste Spawnrate).<br><br>Beachten Sie, dass bestimmte Gegenstands-IDs <b>das Zeichenlimit des Haustiernamens überschreiten können</b>. In solchen Fällen können Sie die Kopier-Schaltfläche dieses Tools verwenden, um das Limit zu umgehen. Es funktioniert, indem es Zeilen aufteilt, um in die Breite des Textfelds zu passen, und den Zeilenumbruchszeichen innerhalb eines Dialogfelds mit dem neuen <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">Dialogbefehl</a> löscht.<br><br><b>Warnung: Verwenden Sie die folgenden Gegenstands-IDs auf eigene Gefahr. Dies kann Ihre Spielerfahrung beeinträchtigen.',
    "tr-TR":
      'Öğeleri oluşturmak için öğe kimliğini karakterinizin adına ekleyerek NPC\'lerle konuşabilir veya <b>Marnie\'den bir evcil hayvan satın alarak</b> öğe kimliğini adına ekleyebilirsiniz.<br><br>Oyunun başlarında, karakter adlarını <b>telefonla Gus ile konuşarak</b> (veya 12:00\'den önce Pierre ile) kolayca tetikleyebilir ve sinemayı açtıktan sonra, <b>Jodi\'yi <a href="https://stardewvalleywiki.com/Jodi#Movies_&amp;_Concessions" target="_blank">Love Concession</a> ile sinemaya davet ederek</b> spamlayabilirsiniz (en hızlı spawn oranı).<br><br>Bazı öğe kimlikleri <b>evcil hayvanın adı karakter sınırını aşabilir</b>. Bu tür durumlarda, bu araç tarafından sağlanan kopyalama düğmesini kullanarak sınırı atlayabilirsiniz. Yeni bir <a href="https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#:~:text=Added%20new%20dialogue%20commands,male%20or%20female" target="_blank">diyalog komutu</a> kullanarak bir diyalog kutusundaki satır kesme karakterini silerek metin kutusunun genişliğine sığacak şekilde satırları böler.<br><br><b>Uyarı: Aşağıdaki öğe kimliklerini kendi sorumluluğunuzda kullanın. Bu, oyun deneyiminizi etkileyebilir.',
  },
  "category-Litter": {
    "en-US": "Litter",
    "pt-BR": "Lixo",
    "ru-RU": "Мусор",
    "ko-KR": "쓰레기",
    "ja-JP": "ゴミ",
    "it-IT": "Spazzatura",
    "hu-HU": "Szemét",
    "fr-FR": "Déchets",
    "es-ES": "Basura",
    "de-DE": "Abfall",
    "tr-TR": "Çöp",
  },
  "category-Basic": {
    "en-US": "Basic",
    "pt-BR": "Básico",
    "ru-RU": "Основной",
    "ko-KR": "기본",
    "ja-JP": "基本",
    "it-IT": "Base",
    "hu-HU": "Alap",
    "fr-FR": "De base",
    "es-ES": "Básico",
    "de-DE": "Grundlegend",
    "tr-TR": "Temel",
  },
  "category-Minerals": {
    "en-US": "Minerals",
    "pt-BR": "Minerais",
    "ru-RU": "Минералы",
    "ko-KR": "광물",
    "ja-JP": "鉱物",
    "it-IT": "Minerali",
    "hu-HU": "Ásványok",
    "fr-FR": "Minéraux",
    "es-ES": "Minerales",
    "de-DE": "Mineralien",
    "tr-TR": "Mineraller",
  },
  "category-Quest": {
    "en-US": "Quest",
    "pt-BR": "Missão",
    "ru-RU": "Задание",
    "ko-KR": "퀘스트",
    "ja-JP": "クエスト",
    "it-IT": "Missione",
    "hu-HU": "Küldetés",
    "fr-FR": "Quête",
    "es-ES": "Misión",
    "de-DE": "Quest",
    "tr-TR": "Görev",
  },
  "category-Crafting": {
    "en-US": "Crafting",
    "pt-BR": "Criação",
    "ru-RU": "Ремесло",
    "ko-KR": "제작",
    "ja-JP": "クラフト",
    "it-IT": "Artigianato",
    "hu-HU": "Készítés",
    "fr-FR": "Artisanat",
    "es-ES": "Creación",
    "de-DE": "Handwerk",
    "tr-TR": "El işi",
  },
  "category-Arch": {
    "en-US": "Arch",
    "pt-BR": "Arco",
    "ru-RU": "Арка",
    "ko-KR": "아치",
    "ja-JP": "アーチ",
    "it-IT": "Arco",
    "hu-HU": "Ív",
    "fr-FR": "Arc",
    "es-ES": "Arco",
    "de-DE": "Bogen",
    "tr-TR": "Kemer",
  },
  "category-Fish": {
    "en-US": "Fish",
    "pt-BR": "Peixe",
    "ru-RU": "Рыба",
    "ko-KR": "물고기",
    "ja-JP": "魚",
    "it-IT": "Pesce",
    "hu-HU": "Hal",
    "fr-FR": "Poisson",
    "es-ES": "Pescado",
    "de-DE": "Fisch",
    "tr-TR": "Balık",
  },
  "category-Cooking": {
    "en-US": "Cooking",
    "pt-BR": "Cozinha",
    "ru-RU": "Кулинария",
    "ko-KR": "요리",
    "ja-JP": "料理",
    "it-IT": "Cucina",
    "hu-HU": "Főzés",
    "fr-FR": "Cuisine",
    "es-ES": "Cocina",
    "de-DE": "Kochen",
    "tr-TR": "Yemek pişirme",
  },
  "category-Seeds": {
    "en-US": "Seeds",
    "pt-BR": "Sementes",
    "ru-RU": "Семена",
    "ko-KR": "씨앗",
    "ja-JP": "種",
    "it-IT": "Semi",
    "hu-HU": "Magok",
    "fr-FR": "Graines",
    "es-ES": "Semillas",
    "de-DE": "Samen",
    "tr-TR": "Tohumlar",
  },
  "category-Ring": {
    "en-US": "Ring",
    "pt-BR": "Anel",
    "ru-RU": "Кольцо",
    "ko-KR": "반지",
    "ja-JP": "リング",
    "it-IT": "Anello",
    "hu-HU": "Gyűrű",
    "fr-FR": "Anneau",
    "es-ES": "Anillo",
    "de-DE": "Ring",
    "tr-TR": "Yüzük",
  },
  "category-asdf": {
    "en-US": "Misc",
    "pt-BR": "Diversos",
    "ru-RU": "Разное",
    "ko-KR": "기타",
    "ja-JP": "その他",
    "it-IT": "Varie",
    "hu-HU": "Vegyes",
    "fr-FR": "Divers",
    "es-ES": "Varios",
    "de-DE": "Verschiedenes",
    "tr-TR": "Çeşitli",
  },
};
